# Generated by Django 4.2.3 on 2023-09-30 19:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_userprofiletype_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileType',
            new_name='UserProfile',
        ),
    ]
