# Generated by Django 4.2.3 on 2023-09-30 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
