# Generated by Django 4.2.3 on 2023-09-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDoctorOperation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalservice',
            name='image',
            field=models.ImageField(upload_to='services/images'),
        ),
    ]
