# Generated by Django 4.2.3 on 2023-09-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('userDoctorOperation', '0002_alter_dentalservice_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DentalService',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(related_name='doctors_specialty', to='base.dentalservice'),
        ),
    ]
