# Generated by Django 4.2.3 on 2023-09-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('userDoctorOperation', '0003_delete_dentalservice_alter_doctor_specialties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(related_name='specialties', to='base.dentalservice'),
        ),
    ]
