# Generated by Django 4.2.3 on 2023-09-29 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userDoctorOperation', '0004_alter_doctor_specialties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='end_time',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='is_booked',
            new_name='isBooked',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='start_time',
            new_name='startTime',
        ),
    ]
