# Generated by Django 4.2.3 on 2023-09-30 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userDoctorOperation', '0005_rename_end_time_slot_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
