# Generated by Django 4.2.3 on 2023-10-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userDoctorOperation', '0006_slot_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentDate', models.DateTimeField(auto_now_add=True)),
                ('paymentMethod', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=10)),
                ('is_successful', models.BooleanField(default=False)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userDoctorOperation.slot')),
            ],
        ),
    ]
